### ISSUE TITLE
[JinJeon] 로그인 여부 확인 기능 구현

### ISSUE THREAD

**Issue by JinJeon** [SHARE-PLATE/frontend#104]
## 📃 Description
사용자의 로그인 여부 확인 및 로그인이 아닐 시 로그인 하도록 기능 구현

## ☑ Todo
- [x] 메인 페이지의 로그인 여부 확인 및 로그인 버튼 보여주기
- [x] 로그인 시에만 볼 수 있는 페이지에 비로그인 회원이 접근 시 로그인 포탈창을 보여주도록 설정
  - [x] 포탈 내에서 스크롤을 할 수 없도록 설정
- [x] profile 페이지 내에서 회원의 정보를 보여주도록 수정
