### ISSUE TITLE
[JinJeon] 채팅 및 알림 관련 에러 수정 및 쉐어 상세 기능 완성

### ISSUE THREAD

**Issue by JinJeon** [SHARE-PLATE/frontend#107]
## 📃 Description
채팅, 알림 소켓 및 쉐어 작성 부분 수정

## ☑ Todo
- [x] 채팅 목록 페이지에서 swipe시 클릭 이벤트가 동작하는 문제 수정
- [x] 채팅 목록 내에 tabs 적용
- [x] 채팅 참여를 위한 쉐어 참여 기능 추가 
- [x] socket을 활용하는 페이지(채팅, 알림)에서 소켓을 통한 데이터 교류 에러 수정
- [x] 쉐어 상세 페이지 내 하단 바 기능 완성
- [x] 쉐어 상세 페이지 디자인 수정 및 적용
