### ISSUE TITLE
[JinJeon] 메뉴 버튼 기능 생성 및 사이드바 렌더링 구현

### ISSUE THREAD

**Issue by JinJeon** [SHARE-PLATE/frontend#11]
## 📃 Description
메뉴(햄버거) 버튼 클릭 시 사이드바가 나오도록 설정 및 사이드바에 애니메이션 적용

## ☑ Todo
- [ ] 메뉴 버튼 클릭 시 사이드바가 생성되도록 설정
- [ ] 사이드바가 열릴 때 우측 → 좌측으로 나오도록 애니메이션 설정
- [ ] 닫기 버튼 또는 사이드바 외부 클릭 시 사이드바가 닫히도록 설정
- [ ] 사이드바가 닫힐 때 좌측 → 우측으로 닫히도록 애니메이션 설정
