### ISSUE TITLE
[JinJeon] 쉐어 지도 페이지 디자인 참고 및 기능 완성

### ISSUE THREAD

**Issue by JinJeon** [SHARE-PLATE/frontend#122]
## 📃 Description
쉐어 지도 페이지 디자인 및 기능 완성하기

## ☑ Todo
- [x] 아래에서 올라오는 스크롤 시 내부 요소가 함께 스크롤되는 문제 수정
- [x] 스크롤 시 외부의 지도가 스크롤의 영향을 받는 문제 수정
- [x] 기타 디자인 관련 차이점 수정
