### ISSUE TITLE
[JinJeon] 채팅 페이지 관련 에러 및 디자인 수정

### ISSUE THREAD

**Issue by JinJeon** [SHARE-PLATE/frontend#125]
## 📃 Description
채팅 페이지 및 채팅 상세 페이지 내에서 발생하는 에러 수정

## ☑ Todo
- [x] 잘못된 채팅 상세 페이지에 들어갈 시 채팅 목록으로 돌아갈 수 있도록 버튼 구성
- [x] 채팅과 관련된 socket 연결 시 나오는 console 제거
- [x] 채팅 상세 헤더에 보이는 채팅 종류, 장소 수정
- [x] 채팅 내용 최상단에 보이는 날짜 수정

**Comment by JinJeon** [comment]
socket console 제거는 notice socket 기능 완성 후 적용!

**Comment by JinJeon** [comment]
소켓 연결이 중간에 끊어진 상황에 대해서 처리 필요
