### ISSUE TITLE
[JinJeon] 알림 페이지 관련 스타일 수정 사항 적용 및 기능 완성

### ISSUE THREAD

**Issue by JinJeon** [SHARE-PLATE/frontend#128]
## 📃 Description
알림 페이지 내에 스타일 변경 사항들 적용, 기존 mock data 적용 부분들을 수정

## ☑ Todo
- [x] 알림 삭제 관련 스타일 변경 사항 적용
- [x] mock data 적용된 부분들을 실제 데이터로 보여주도록 수정
- [x] 알림별 링크 기능 적용

**Comment by JinJeon** [comment]
소켓 리펙토링 필요합니다!
