### ISSUE TITLE
[JinJeon] Socket 관련 세부 설정

### ISSUE THREAD

**Issue by JinJeon** [SHARE-PLATE/frontend#134]
## 📃 Description
Socket 연결 방식 및 세부 설정 변경

## ☑ Todo
- [x] 채팅 및 알림 관련 소켓이 한 번에 연결되도록 설정 변경
- [x] 소켓 자체의 연결이 끊어지는 경우에 대한 처리 설정
- [x] 소켓 연결 각각에 대한 끊기 기능이 가능하도록 소켓 컴포넌트 리펙토링
