### ISSUE TITLE
[JinJeon] 배포를 위한 기타 에러 수정

### ISSUE THREAD

**Issue by JinJeon** [SHARE-PLATE/frontend#139]
## 📃 Description
배포 전 기타 에러 사항 수정

## ☑ Todo
- [x] 스타일 관련 작은 문제들 수정
- [x] https로 api 적용 방식 변경
- [x] back title button에 option 추가 적용 가능하도록 설정
