### ISSUE TITLE
[JinJeon] 메인 페이지 광고 carousel 구현

### ISSUE THREAD

**Issue by JinJeon** [SHARE-PLATE/frontend#14]
## 📃 Description
메인 페이지의 광고 영역에 여러 광고들을 보여주는 carousel 구현

## ☑ Todo
- [x] 메인 페이지의 헤더 바로 아래에 광고 영역 생성 및 페이지 진입 시 바로 광고 carousel이 보이도록 설정
- [x] carousel의 양쪽 화살표 클릭 시 각 방향의 광고들을 보여주도록 설정
- [x] 광고가 특정 시간 단위마다 자동으로 넘어가도록 설정
- [x] carousel 하단에 광고의 순서를 나타내는 아이콘 설정
- [x] 광고 순서 아이콘 클릭 시 각 아이콘에 대한 광고로 넘어가도록 설정
