### ISSUE TITLE
[JinJeon] socket 사용 페이지 기능 수정 및 사파리 호환성 위한 수정

### ISSUE THREAD

**Issue by JinJeon** [SHARE-PLATE/frontend#141]
## 📃 Description
채팅 ∙ 알림 페이지 내의 연결 재시도 및 알림 설정 변경 및 사파리 브라우저의 호환성 위한 스타일 변경

## ☑ Todo
- [x] socket 연결 차단 시 재시도하도록 설정
- [x] 알림 내에 socket 차단에 대한 알림 기능 설정
- [x] 사파리 내 가로 글씨가 세로로 나오는 문제 수정
- [x] 사파리 내 http 요청을 받아오지 못하는 문제 수정
