### ISSUE TITLE
[JinJeon] 쉐어 상세 및 로그아웃 페이지 기능 추가

### ISSUE THREAD

**Issue by JinJeon** [SHARE-PLATE/frontend#147]
## 📃 Description
쉐어 상세에서 특정 상황에 대한 기능 추가 ∙ 로그아웃 시 확인을 위한 모달창 추가

## ☑ Todo
- [x] 로그아웃 버튼 클릭 시 확인 여부를 묻는 모달창이 나오도록 설정
- [x] 로그아웃 성공 ∙ 실패 여부에 따른 알림 설정 추가
- [x] 쉐어 상세 페이지 내 참가 ∙ 참가 취소 상황에 대한 실제 반영 추가
- [x] 쉐어 상세 페이지 내 데이터 받아오기 실패 상황에 대한 처리 추가
