### ISSUE TITLE
[JinJeon] 더보기 기능 활성화

### ISSUE THREAD

**Issue by JinJeon** [SHARE-PLATE/frontend#153]
## 📃 Description
'더보기' 버튼을 클릭할 시 해당 제목과 관련된 링크로 이동하도록 설정

## ☑ Todo
- [x] 메인 페이지 내 더보기 기능 활성화
- [x] 프로필 페이지 내 더보기 기능 활성화
- [x] 더보기 버튼 클릭, 호버에 대한 CSS 추가
