### ISSUE TITLE
[JinJeon] 페이지 초기 진입 시 주소 설정 방식 변경

### ISSUE THREAD

**Issue by JinJeon** [SHARE-PLATE/frontend#155]
## 📃 Description
페이지에 초기에 진입하는 상황 시 지정된 주소가 있을 경우 추가적인 주소 변경이 없도록 설정

## ☑ Todo
- [x] 페이지 진입 시 localStorage 내의 주소 설정 정보 확인 후 적용
- [x] localStorage 내에 주소 설정이 없는 경우, 현재 주소로 등록하도록 설정
- [x] 주소 설정 페이지 내에서 주소 설정 시 localStorage 내에 해당 주소 저장하도록 설정
