### ISSUE TITLE
[JinJeon] Navigation Bar 컴포넌트 생성 및 기능 구현

### ISSUE THREAD

**Issue by JinJeon** [SHARE-PLATE/frontend#18]
## 📃 Description
Navigation Bar가 하단에 생성되며, 각 버튼마다 기능이 동작하도록 구현

## ☑ Todo
- [x] 모바일 상황에서 하단에 네비게이션 바가 나오도록 설정
- [x] '검색' 버튼을 제외한 모든 버튼이 해당 링크로 이동하도록 설정
- [x] '검색' 버튼 클릭 시 검색창의 내용이 담긴 화면을 덮는 모달창이 나오도록 설정
