### ISSUE TITLE
[JinJeon] 검색창 기능 완성 및 쉐어 등록 이동 버튼 생성

### ISSUE THREAD

**Issue by JinJeon** [SHARE-PLATE/frontend#24]
## 📃 Description
검색창의 세부 기능 완성 및 쉐어 등록 페이지를 제외한 모든 페이지에서 보여지는 쉐어 등록 이동 버튼 생성

## ☑ Todo
- [x] 검색창에서 검색어를 입력 시 검색어가 저장된 후 모달창이 사라지도록 설정
- [x] 검색어 우측의 X버튼 클릭 시 해당 검색어가 사라지도록 설정
- [x] 검색창 디자인 완성
- [x] '전체 삭제' 버튼 클릭 시 모든 검색어가 사라지도록 설정
- [x] 쉐어 등록 페이지가 아닐 시, 네비게이션 바 우측 상단에 쉐어 등록 이동 버튼이 생기도록 설정
