### ISSUE TITLE
[JinJeon] 스타일 테마 색상, 스타일 지정 및 너비 설정

### ISSUE THREAD

**Issue by JinJeon** [SHARE-PLATE/frontend#30]
## 📃 Description
전반적으로 사용되는 색상, 폰트, 너비 등 스타일 요소 지정

## ☑ Todo
- [x] font-family, font-size 설정 
- [x] 테마 색상 지정 및 적용
- [x] 전반적인 모바일 비율의 너비 지정 및 스타일 적용
