### ISSUE TITLE
[JinJeon] login 컴포넌트 생성 및 profile 디자인 수정

### ISSUE THREAD

**Issue by JinJeon** [SHARE-PLATE/frontend#31]
## 📃 Description
portal 컴포넌트 활용성을 위해 리펙토링 진행 및 이를 이용한 login 컴포넌트 재생성

## ☑ Todo
- [x] portal 컴포넌트 사용 시 portal name, portal type을 이용해 즉각 적용 가능하도록 설정
- [x] login 컴포넌트 생성
- [x] profile 컴포넌트 디자인 수정 및 적용
