### ISSUE TITLE
[JinJeon] 메인 페이지 광고 리펙토링 및 항목 추가

### ISSUE THREAD

**Issue by JinJeon** [SHARE-PLATE/frontend#38]
## 📃 Description
메인 페이지 시간이 얼마 남지 않은 목록 생성

## ☑ Todo
- [x] 남은 시간 구하는 util 함수 생성
- [x] 메인 페이지 광고 부분 스타일 리펙토링
- [x] 메인 페이지 시간이 얼마 남지 않은 항목 생성
