### ISSUE TITLE
[JinJeon] 메인 페이지 완성

### ISSUE THREAD

**Issue by JinJeon** [SHARE-PLATE/frontend#45]
## 📃 Description
메인 페이지 기능 완성 및 일부 스타일 수정

## ☑ Todo
- [x] 메인 페이지 데이터 불러오도록 기능 추가
- [x] 메인 페이지 재료 쉐어 ∙ 배달 쉐어 리스트 불러오기 및 보여주기 기능 추가
- [x] 기타 스타일 수정
