### ISSUE TITLE
[JinJeon] 쉐어 상세 페이지 하단 레이아웃 및 기타 스타일링

### ISSUE THREAD

**Issue by JinJeon** [SHARE-PLATE/frontend#49]
## 📃 Description
쉐어 상세 페이지 하단 레이아웃 생성 및 기타 스타일링

## ☑ Todo
- [x] 하단 네비게이션 바 영역에 쉐어 상세일 시 해당 쉐어 관련 버튼 보여주도록 설정 
- [x] 쉐어 주최자의 쉐어 리스트 보여주도록 설정
- [x] 추천 쉐어 목록 보여주도록 설정
- [x] 변경된 스타일 적용
