### ISSUE TITLE
[Khan] 마이페이지 판매내역 구매내역

### ISSUE THREAD

**Issue by Han-Seung-Chan** [SHARE-PLATE/frontend#71]
## 📃 Description
마이페이지 판매내역 구매내역.

## ☑ Todo
- [ ] 유저 정보 확인
- [ ] 현재 판매하고 있는 내역  보여주기
- [ ] 현재 구매하고 있는 내역 보여지구
- [ ] 기간 만료 된 쉐어 표시
