### ISSUE TITLE
[JinJeon] image container 컴포넌트 생성 및 적용 및 share form button 리펙토링

### ISSUE THREAD

**Issue by JinJeon** [SHARE-PLATE/frontend#79]
## 📃 Description
image container 컴포넌트 생성 및 적용 및 share form button 리펙토링

## ☑ Todo
- [x] 이미지 크기에 맞게 들어오는 container 생성
- [x] 이미지 적용된 곳에 컴포넌트 사용
- [x] share form button 적용 시 클릭되지 않는 문제 수정
- [x] share form button이 화면 크기와 무관하게 고정되도록 설정
