### ISSUE TITLE
[JinJeon] Portal 컴포넌트 생성 및 로그인 버튼 적용

### ISSUE THREAD

**Issue by JinJeon** [SHARE-PLATE/frontend#8]
## 📃 Description
재사용 가능한 Portal 컴포넌트 생성 및 로그인 버튼 클릭 시 Portal 컴포넌트가 나오도록 적용

## ☑ Todo
- [x] Portal 컴포넌트 생성
- [x] 로그인 클릭 시 Portal 컴포넌트 렌더링
- [x] Portal 외부 클릭 시 Portal 닫힘
- [x] 나타나기 ∙ 사라지기 애니메이션 구현
