### ISSUE TITLE
[Khan] 이슈 추가 페이지 옵션 선택 기능 추가

### ISSUE THREAD

**Issue by Han-Seung-Chan** [SHARE-PLATE/frontend#81]
## 📃 Description
이슈 추가 페이지 옵션 선택 기능 추가
## ☑ Todo
- [x] 옵션 버튼 추가
- [x] 인원 선택 추가
- [x] 사진 미리보기 추가
- [x] 시가 선택 추가
