### ISSUE TITLE
[JinJeon] 알림센터 레이아웃 생성

### ISSUE THREAD

**Issue by JinJeon** [SHARE-PLATE/frontend#88]
## 📃 Description
알림센터 레이아웃 생성

## ☑ Todo
- [x] 알림 버튼 클릭 시 알림센터 페이지가 나오도록 설정
- [x] tabs 컴포넌트의 재사용성을 위한 tabs 컴포넌트, share list 페이지 리펙토링
- [x] 사용자가 클릭 시 이동하는 활동알림 ∙ 키워드알림 버튼 설정
- [x] 클릭된 종류에 따른 알림 내용들이 보여지도록 설정
