### ISSUE TITLE
[JinJeon] socket 및 채팅 관련 리펙토링 및 알림을 위한 socket 설정

### ISSUE THREAD

**Issue by JinJeon** [SHARE-PLATE/frontend#95]
## 📃 Description
알림 기능을 위한 socket 설정

## ☑ Todo
- [x] socket 분리 및 리펙토링
- [x] 채팅 내에서 사용된 socket의 내용 중 에러가 있는 부분 리펙토링 (첫 채팅 입장 시 socket 접속 안되는 문제 등)
- [x] 모든 페이지에서 알림을 받기 위한 socket 기능 설정
